=== Arrocito82/ejercicio4/Ejercicios/dtd_externa/dtd/ejercicioII.2a.dtd
<!ELEMENT fichero (ficha+)>
<!ELEMENT ficha (nombre, apellido, direccion*, DUI,contactos)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre sexo (M|F|m|f) #FIXED "f" edad  CDATA  #IMPLIED>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT DUI (#PCDATA)>
<!ELEMENT contactos (telefono|facebook|instagram|twitter)+>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo (fijo|celular) #REQUIRED>
<!ELEMENT facebook (#PCDATA)>
<!ELEMENT instagram (#PCDATA)>
<!ELEMENT twitter (#PCDATA)>

=== Arrocito82/ejercicio4/Ejercicios/dtd_externa/ejercicioII.2a.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="css/ejercicio-ii-1a-dtd" type="text/css"?>
<!-- ejercicio II.2a.xml -->
<!DOCTYPE fichero SYSTEM "dtd/ejercicioII.2a.dtd">
<fichero>
 <ficha>
  <nombre sexo="f" edad="17" >Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
  <DUI>02020202-2</DUI>
  <contactos>
  <telefono tipo="celular">70000000</telefono>
  <facebook>Angelina Fernandez</facebook>
  <instagram>Angelina Fernandez</instagram>
  <twitter>@angelinafernandez50</twitter>
  </contactos>

 </ficha>
</fichero>
